spring.application.name=ms-seguridad
server.servlet.context-path=/apis/codigo
#server.port=8081
#spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
#spring.datasource.username=postgres
#spring.datasource.password=admin
#postgresql://neondb_owner:npg_TPqIOAM5ns7b@ep-billowing-block-ac631ukw-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#logging.level.root= info
server.port=${PORT:8081}
logging.level.root= info 
#token.api=sk_7701.y0uLrT7FJyzCkN2zotD3R23j02ZMYoRU
#token.api=sk_13418.psSRgwTWR1b0oTq5I8tSVVQ4JDNWTilF

#key.signature=XloYDteI0LNOvqDrsuRXInD/TNlkxh0Y8cWKSrmk9pwxT2UQxVqEKDt5IJHR3kWYOndi1wnXhgutCII6drunxw==
##recuerda que estas son como variables de entorno con las cuales uno deve trabajar si?
#app.message=HOLA MUNDO
key.signature=${JWT_SECRET}
#recuerda que estas son como variables de entorno con las cuales uno deve trabajar si?
app.message=${APP_MESSAGE:HOLA MUNDO}